trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  acrName: 'psacontainer'

steps:

- checkout: self

# Install .NET
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore API
- script: |
    dotnet restore platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Api/PlatformEngineer.Api.csproj
  displayName: 'Restore API'

# Restore Worker
- script: |
    dotnet restore platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Worker/PlatformEngineer.Worker.csproj
  displayName: 'Restore Worker'

# Build API
- script: |
    dotnet build platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Api/PlatformEngineer.Api.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build API'

# Build Worker
- script: |
    dotnet build platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Worker/PlatformEngineer.Worker.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build Worker'

# Login ACR
- task: AzureCLI@2
  displayName: 'ACR Login'
  inputs:
    azureSubscription: 'platform-azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(acrName)

# Build & Push API Image
- script: |
    docker build -t $(acrName).azurecr.io/platformengineer-api:$(Build.BuildId) \
  -f PlatformEngineer.Api/Dockerfile \
  PlatformEngineerAssessment

    docker push $(acrName).azurecr.io/platformengineer-api:$(Build.BuildId)
  displayName: 'Build & Push API'

# Build & Push Worker Image
- script: |
    docker build -t $(acrName).azurecr.io/platformengineer-api:$(Build.BuildId) \
  -f PlatformEngineer.Api/Dockerfile \
  PlatformEngineerAssessment

    docker push $(acrName).azurecr.io/platformengineer-worker:$(Build.BuildId)
  displayName: 'Build & Push Worker'

# Deploy API
- task: AzureCLI@2
  displayName: 'Deploy API'
  inputs:
    azureSubscription: 'platform-azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp up \
        --name platform-api \
        --resource-group platform-rg \
        --environment platform-container-env \
        --image $(acrName).azurecr.io/platformengineer-api:$(Build.BuildId) \
        --target-port 80 \
        --ingress external \
        --registry-server $(acrName).azurecr.io

# Deploy Worker
- task: AzureCLI@2
  displayName: 'Deploy Worker'
  inputs:
    azureSubscription: 'platform-azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp up \
        --name platform-worker \
        --resource-group platform-rg \
        --environment platform-container-env \
        --image $(acrName).azurecr.io/platformengineer-worker:$(Build.BuildId) \
        --registry-server $(acrName).azurecr.io