trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self

# Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore API
- script: |
    dotnet restore PlatformEngineer.Api/PlatformEngineer.Api.csproj
  displayName: 'Restore API'

# Restore Worker
- script: |
    dotnet restore PlatformEngineer.Worker/PlatformEngineer.Worker.csproj
  displayName: 'Restore Worker'

# Build API
- script: |
    dotnet build PlatformEngineer.Api/PlatformEngineer.Api.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build API'

# Build Worker
- script: |
    dotnet build PlatformEngineer.Worker/PlatformEngineer.Worker.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build Worker'

# Publish API
- script: |
    dotnet publish PlatformEngineer.Api/PlatformEngineer.Api.csproj \
      -c $(buildConfiguration) \
      -o $(Build.ArtifactStagingDirectory)/api
  displayName: 'Publish API'

# Publish Worker
- script: |
    dotnet publish PlatformEngineer.Worker/PlatformEngineer.Worker.csproj \
      -c $(buildConfiguration) \
      -o $(Build.ArtifactStagingDirectory)/worker
  displayName: 'Publish Worker'

# Docker Compose Build
- script: |
    docker compose build
  displayName: 'Docker Compose Build'

# Run Containers
- script: |
    docker compose up -d
    docker ps
  displayName: 'Run Containers'

# Publish Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'