trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- checkout: self

# Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore API
- script: |
    dotnet restore platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Api/PlatformEngineer.Api.csproj
  displayName: 'Restore API'

# Restore Worker
- script: |
    dotnet restore platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Worker/PlatformEngineer.Worker.csproj
  displayName: 'Restore Worker'

# Build API
- script: |
    dotnet build platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Api/PlatformEngineer.Api.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build API'

# Build Worker
- script: |
    dotnet build platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Worker/PlatformEngineer.Worker.csproj \
      --configuration $(buildConfiguration) \
      --no-restore
  displayName: 'Build Worker'

# Publish API
- script: |
    dotnet publish platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Api/PlatformEngineer.Api.csproj \
      -c $(buildConfiguration) \
      -o $(Build.ArtifactStagingDirectory)/api
  displayName: 'Publish API'

# Publish Worker
- script: |
    dotnet publish platform-engineer-assessment/PlatformEngineerAssessment/PlatformEngineer.Worker/PlatformEngineer.Worker.csproj \
      -c $(buildConfiguration) \
      -o $(Build.ArtifactStagingDirectory)/worker
  displayName: 'Publish Worker'

# Docker Compose Build
- script: |
    cd platform-engineer-assessment/PlatformEngineerAssessment
    docker compose build
  displayName: 'Docker Compose Build'

# Run Containers
- script: |
    cd platform-engineer-assessment/PlatformEngineerAssessment
    docker compose up -d
    docker ps
  displayName: 'Run Containers'

# Deploy API
- task: AzureCLI@2
  displayName: 'Deploy API'
  inputs:
    azureSubscription: 'platform-azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az containerapp up \
        --name platform-api \
        --resource-group platform-rg \
        --environment platform-container-env \
        --image psacontainer.azurecr.io/platformengineer-api:$(Build.BuildId) \
        --target-port 80 \
        --ingress external \
        --registry-server psacontainer.azurecr.io

# Deploy Worker
- task: AzureCLI@2
  displayName: 'Deploy Worker'
  inputs:
    azureSubscription: 'platform-azure-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az containerapp up \
        --name platform-worker \
        --resource-group platform-rg \
        --environment platform-container-env \
        --image psacontainer.azurecr.io/platformengineer-worker:$(Build.BuildId) \
        --registry-server psacontainer.azurecr.io

# Publish Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'