version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: PlatformEngineer.Api/Dockerfile
    image: platform-api-local:dev
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AZURE_SERVICEBUS_CONNECTION_STRING=${AZURE_SERVICEBUS_CONNECTION_STRING}
      - SERVICEBUS_QUEUE_NAME=${SERVICEBUS_QUEUE_NAME:-workitems}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - TABLE_NAME=${TABLE_NAME:-processeditems}
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: PlatformEngineer.Worker/Dockerfile
    image: platform-worker-local:dev
    environment:
      - AZURE_SERVICEBUS_CONNECTION_STRING=${AZURE_SERVICEBUS_CONNECTION_STRING}
      - SERVICEBUS_QUEUE_NAME=${SERVICEBUS_QUEUE_NAME:-workitems}
      - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      - TABLE_NAME=${TABLE_NAME:-processeditems}
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: >
      azurite
      --blobHost 0.0.0.0 --blobPort 10000
      --queueHost 0.0.0.0 --queuePort 10001
      --tableHost 0.0.0.0 --tablePort 10002